### ISSUE TITLE
Build Fail

### ISSUE THREAD

**Issue by TianzhuQin** [simile-widgets/timeline#8]
I am sorry that I cannot use ant to make it here. The following warnings come out. Could you please help me to check that? I think it is because some files disappear.

(base) TianzhuQins-MacBook-Pro:trunk optboy$ ant
Buildfile: /Users/optboy/Downloads/html_local/trunk/build.xml

tasks:

bundle:

tasks:

parameterized-bundle:

tasks:

parameterized-bundle:

compile:

compile-ajax:

BUILD FAILED
/Users/optboy/Downloads/html_local/trunk/build.xml:114: The following error occurred while executing this line:
/Users/optboy/Downloads/html_local/trunk/build.xml:72: java.io.FileNotFoundException: /Users/optboy/Downloads/html_local/trunk/src/ajax/api/compilations/simile-ajax-compilation.js (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at edu.mit.simile.jsminTask.JSMinTask.execute(JSMinTask.java:89)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:106)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
	at org.apache.tools.ant.Main.runBuild(Main.java:830)
	at org.apache.tools.ant.Main.startAnt(Main.java:223)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)

Total time: 1 second

**Comment by KnowledgeGarden** [comment]
Files seem to be missing in src:
BUILD FAILED
/Users/jackpark/Documents/gitprojects5/TIMELINE/SIMILE/timeline-master/build.xml:25: taskdef class edu.mit.simile.jsminTask.JSMinTask cannot be found
 using the classloader AntClassLoader[]

The task identified in the error message calls for this classpath
classpath="tools/jsmin-task/jsminTask.jar"

There is no jsminTask.jar in this master.

**Comment by KnowledgeGarden** [comment]
This is getting serious: I wonder if anyone is actually using this codebase. I found the missing jar in an older version and dropped that in. Now, I get a new fatal error
This classpath does not exist: there is no src/ajax directory
 <property name="ajax_api" value="src/ajax/api

either in the master build or the older version.

**Comment by jonassmedegaard** [comment]
> I wonder if anyone is actually using this codebase.

Debian distributes a build which is used at least for https://timeline.debian.net/ - development information about that package is at https://tracker.debian.org/pkg/simile-timeline

**Comment by jonassmedegaard** [comment]
Possibly most interesting for someone outside Debian is to explore the patches applied as part of the Debian packaging - some of those might be helpful more generally: https://salsa.debian.org/js-team/simile-timeline/-/tree/debian/master/debian/patches
